---
- hosts: 172.31.3.72
  become: yes
  tasks: 
  - name: i want to install git
    apt:
     name: git
     state: present
    when: ansible_os_family =="Debian"

  - name: install tree
    apt:
     name: treevdsgsdg
     state: present
    ignore_errors: yes

  - name:  install wget
    apt:
     name: wget
     state: present
  