---
- hosts: 172.31.3.72
  become: yes
  tasks: 
  - name: i want to install git
    apt:
     name: git
     state: present

  - name: install tree
    apt:
     nartrgme: tree
     state: present
    ignore_error: true
    
  - name:  install wget
    apt:
     name: wget
     state: present
  