---
- hosts: 172.31.3.72
  become: yes
  tasks: 
  - name: i want to install git
    apt:
     name: git
     state: present
  
  - name: install tree
    apt:
     name: treesfsdf
     state: present
    ignore_error: yes
  
  - name:  install wget
    apt:
     name: wget
     state: present
  