---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i install java  on ubuntu
    apt:
     name: "{{myjavapackonubuntu}}"
     state: present
    when: ansible_os_family =="Debian"
  - name: i install java on RedHat
    yum:
     name: "{{myjavapackonredhat}}"
     state: present
    when: ansible_os_family =="RedHat"