---
- hosts:  172.31.3.72
  become: yes
  tasks:
  - name: i want to install git
    apt:
     name: git
     state: present
   

  - name: install wget
    apt:
      name: wgetfhfdhdfhfds
      state: present
    ignore_errors: True

  - name: instll tree
    apt:
     name: tree
     state: present
 
