---
- hosts:  172.31.3.72
  become: yes
  tasks:
  - name: i want to install git
    apt:
     name: git
     state: present
    tags: mygit
   

  - name: install wget
    apt:
      name: wget
      state: present
    tags: mywget

  - name: instll tree
    apt:
     name: tree
     state: present
    tags: tree
 
