---
- name: cpy user file into node side
  template:
      src: template/mytomcatuser.j2
      dest: /opt/tomcat/conf/tomcat-users.xml

- name: cpy context file into node side
  template: 
      src: template/mycontext.j2
      dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: cpy context file into node side
  template: 
      src: template/myhostcontext.j2
      dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml
